# The necessary configuration file for Cloudflare Pages
name = "zillion-website"

compatibility_date = "2024-05-16"

# Build configuration
[build]
command = "npm run build"
output_directory = "out"  # This is where Next.js exports static files

# Environment variables
[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "development"
