name = "zillionsystems-website"
type = "webpack"
account_id = "your-account-id" # Replace with your Cloudflare account ID
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-10-30"

[site]
bucket = ".next/static"
entry-point = "workers-site"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
name = "zillionsystems-website-prod"
route = "yourdomain.com/*"
zone_id = "your-zone-id" # Replace with your Cloudflare zone ID
